### ISSUE TITLE
allow login on Enter press in the Password Form Field

### ISSUE THREAD

**Issue by arpu** [vrlandio/issues#177]
allow login on Enter press in the Password Form Field

and on register

**Comment by bpeterme** [comment]
ok, just to confirm, this is for the password field in the "sign-in" form, right? because for "enter as guest" and "join" forms the last element is the gender switch which should not be skipped with on Enter press.

**Comment by arpu** [comment]
yes for the "sign-in" form!

**Comment by bpeterme** [comment]
done with https://github.com/vrlandio/vrland_app/commit/042372a5cce96ddc0e850ee6a561f2b7f2d05210
